using System;

namespace HM2.NonAutoGenerated
{
    //public class MovableAdapterNotAuto : HM2.GameSolve.Interfaces.IMovable
    //{
    //    HM2.MovableObject.UObject obj;
    //    public MovableAdapterNotAuto(HM2.MovableObject.UObject obj)
    //    {
    //        this.obj = obj;
    //    }
    //    public HM2.GameSolve.Structures.Vector getPosition()
    //    {
    //        return HM2.IoCs.IoC<Func<HM2.MovableObject.UObject, HM2.GameSolve.Structures.Vector>>.Resolve("Movable_position").Invoke(obj);
    //    }
    //    public HM2.GameSolve.Structures.Vector getVelocity()
    //    {
    //        return HM2.IoCs.IoC<Func<HM2.MovableObject.UObject, HM2.GameSolve.Structures.Vector>>.Resolve("Movable_velosity").Invoke(obj);
    //    }
    //    public HM2.GameSolve.Structures.Vector setPosition(HM2.GameSolve.Structures.Vector newValue)
    //    {
    //        return HM2.IoCs.IoC<Func<HM2.MovableObject.UObject, HM2.GameSolve.Structures.Vector, HM2.GameSolve.Structures.Vector>>.Resolve("Movable_position_set").Invoke(obj, newValue);
    //    }
    //}
}
